from copy import deepcopy


VALID_CONFIG = {
    "mode": "demo",
    "llm": {
        "provider": "anthropic",
        "model": "test-model",
        "temperature": 0.2,
        "max_tokens": 2000,
    },
    "strategy": {
        "id": "momentum",
        "version": "phase1-v2",
        "signal_timeframe": "15m",
        "allow_experimental_setups_in_demo": True,
        "setup_cooldown_minutes": 45,
        "setup_memory_hours": 72,
        "loss_reentry_min_minutes": 60,
        "min_stop_atr_multiple": 1.0,
        "structure_buffer_atr_multiple": 0.15,
        "hard_max_entry_extension_atr": 2.5,
        "breakout_range_threshold_pct": 85,
        "breakout_min_relative_volume": 1.0,
        "funding_extreme_pct_per_8h": 0.01,
        "fixed_reward_risk": 2.0,
        "extended_reward_risk": 3.0,
    },
    "universe": {
        "top_n": 10,
        "min_24h_quote_volume_usd": 50_000_000,
        "min_history_candles": 60,
        "denylist": [],
        "refresh_minutes": 60,
    },
    "cycle": {
        "interval_seconds": 300,
        "timeframes": ["15m", "1h", "4h"],
        "candles": 120,
    },
    "risk": {
        "max_leverage": 3,
        "entry_leverage": 2,
        "risk_per_trade_pct": 1.5,
        "experimental_risk_per_trade_pct": 0.5,
        "max_total_open_risk_pct": 3.0,
        "max_position_notional_pct": 30,
        "max_gross_exposure_pct": 150,
        "max_net_direction_pct": 100,
        "max_btc_beta_exposure_pct": 100,
        "min_btc_beta_samples": 24,
        "max_concurrent_positions": 3,
        "min_confidence": 0.65,
        "max_hold_hours": 24,
        "daily_loss_limit_pct": 5,
        "flatten_on_daily_stop": False,
        "max_drawdown_pct": 15,
        "max_margin_usage_pct": 60,
        "min_maintenance_margin_ratio": 3.0,
        "min_stop_liquidation_buffer_pct": 1.0,
        "cooldown_minutes_after_loss": 45,
    },
    "execution": {
        "slippage_guard_pct": 0.5,
        "max_spread_pct": 0.15,
        "max_order_book_slippage_pct": 0.35,
        "max_market_data_age_seconds": 10,
        "fill_timeout_seconds": 1,
        "liquidity_feedback_ttl_minutes": 30,
        "liquidity_retries_before_backoff": 1,
        "liquidity_backoff_minutes": 15,
        "liquidity_depth_buffer_pct": 70,
        "entry_failure_backoff_minutes": 15,
        "entry_failure_backoff_max_minutes": 60,
        "entry_failure_ttl_minutes": 240,
    },
    "trading_costs": {
        "taker_fee_pct_per_side": 0.05,
        "expected_stop_slippage_pct": 0.15,
        "expected_funding_intervals_held": 1,
        "expected_hold_hours": 8,
    },
    "alerts": {
        "enabled": False,
        "webhook_url_env": "ALERT_WEBHOOK_URL",
        "format": "generic",
        "minimum_level": "error",
        "timeout_seconds": 5,
    },
}


def valid_config() -> dict:
    return deepcopy(VALID_CONFIG)
