"""Crowded positioning unwinding, identified by funding percentile.

Same entry rule as funding_carry, opposite economics. That is deliberate and
is the point: funding-carry claimed the carry was the return source and was
falsified at 2% attribution, so this registers the opposite claim - the
carry is incidental and the return comes from price as crowded positioning
unwinds. The attribution gate is what distinguishes them, and sharing the
entry rule is what makes the comparison clean.

Mechanism: crowded leveraged positions are unstable. They are held by
traders who need the move to continue in order to keep affording the
position, and who are forced out when it does not. The payer is the crowded
leveraged trader squeezed out of a position they could not finance.

PROVENANCE: generated by decomposing funding-carry's result on the same
window it was measured on, so any number from that window is in-sample by
construction. See research/hypotheses/funding-unwind.yaml.
"""

from __future__ import annotations

from . import finite as _finite, register


def setup_evidence(snapshot: dict, cfg: dict) -> dict:
    block = cfg["strategy"]
    atr = max(_finite(snapshot.get("atr_1h_pct"), 0.0) or 0.0, 0.0)
    ema_distance = _finite(snapshot.get("ema20_1h_dist_pct"), 0.0) or 0.0
    long_extension = max(0.0, ema_distance / atr) if atr > 0 else None
    short_extension = max(0.0, -ema_distance / atr) if atr > 0 else None

    funding = _finite(snapshot.get("funding_rate_pct"))
    interval = _finite(snapshot.get("funding_interval_hours"))
    if interval is None or interval <= 0:
        interval = 8.0
    funding_8h = funding * (8.0 / interval) if funding is not None else None
    percentile = _finite(snapshot.get("funding_percentile_30"))
    samples = int(max(0.0, _finite(snapshot.get("funding_samples_30"), 0.0)
                      or 0.0))
    trend_1h = snapshot.get("trend_1h")
    trend_4h = snapshot.get("trend_4h")

    floor = float(block["funding_extreme_pct_per_8h"])
    high = float(block.get("unwind_percentile", 80.0))
    min_samples = int(block.get("unwind_min_samples", 20))

    context = (samples >= min_samples and percentile is not None
               and funding_8h is not None)

    # Funding high in its own range means longs are crowded, so the unwind
    # is downward. Refuse when both higher timeframes still trend up: a
    # crowded trade that is still working can stay crowded for a long time,
    # and this contract is not paid to wait through that.
    short_ = (context and funding_8h >= floor and percentile >= high
              and not (trend_1h == "up" and trend_4h == "up"))
    long_ = (context and funding_8h <= -floor
             and percentile <= (100 - high)
             and not (trend_1h == "down" and trend_4h == "down"))
    return {
        "positioning_unwind": {"long": long_, "short": short_},
        "extension_atr": {
            "long": round(long_extension, 2)
            if long_extension is not None else None,
            "short": round(short_extension, 2)
            if short_extension is not None else None,
        },
        "hard_no_chase_atr": float(block["hard_max_entry_extension_atr"]),
        "funding_percentile_30": percentile,
    }


register("funding-unwind", setup_evidence)
